const CONFIG = {
    introTitle: 'Vân Anh ơiii!',
    introDesc: `Chơi trò này với e nè',
    btnIntro: 'hihi',
    title: 'Chị trả lời đii 😙',
    desc: 'Chị có thích e hong',
    btnYes: 'Dạ có <33',
    btnNo: 'Honggg:3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi anh <3',
    reply: 'Hong biếttt',
    mess: 'Iu chị nhìuuu 😘😘',
    messDesc: 'Tối chơi game với e hong.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'http://fb.com' //link mess của các bạn. VD: https://m.me/nam.nodemy}
