const CONFIG = {
    introTitle: 'Vân Anh ơiii!',
    introDesc: `chơi trò này với e nèe',
    btnIntro: 'hihi',
    title: 'Chị trả lời đi nèee 😙',
    desc: 'Chị có thích e honggg ',
    btnYes: 'Dạ có <33',
    btnNo: 'hong ee :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Iu chị nhiềuuu 😘😘',
    messDesc: 'Tối chơi game với e hong.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'http://fb.com' //link mess của các bạn. VD: https://m.me/nam.nodemy}
