const CONFIG = {
    introTitle: 'Vân Anh ơii!',
    introDesc: `chơi trò này với e nè',
    btnIntro: 'hihi',
    title: 'Chị trả lời điiiii 😙',
    desc: 'Chị có thích e hong ',
    btnYes: 'Dạ có <33',
    btnNo: 'hong ee :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi anh <3',
    reply: 'Hong biếttttt',
    mess: 'Iu chị nhiềuuu 😘😘',
    messDesc: 'Tối chơi game với e hong.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'http://fb.com' //link mess của các bạn. VD: https://m.me/nam.nodemy}
